version: 2
updates:
  # python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    groups:
      all-dependencies:
        # Dependabot uses a lot of heuristic matching, so it's not clear if we can separate prod from dev
        exclude-patterns:
          # We need to manually maintain all of our dbt and internal MetricFlow sub-package dependencies
          - "dbt-*"
          - "metricflow*"
          # Manually exclude annoying-to-update dev dependencies
          - "ruff"
          - "pre-commit"
          - "black"

  # GitHub actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
