name: JSON Schema Consistency Check
on:
  workflow_dispatch:

  pull_request:
    # run these jobs when a PR is opened, reopened, or updated (synchronize)
    # synchronize = commit(s) pushed to the pull request
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - "dbt_semantic_interfaces/**"

jobs:
  json-schema-consistency-check:
    name: Schema Consistency Check
    strategy:
      matrix:
        python-version: ["3.8", "3.12"]
    runs-on: ubuntu-latest
    steps:
      - name: Check-out the repo
        uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }} env
        uses: ./.github/actions/setup-python-env
        with:
          python-version: ${{ matrix.python-version }}

      - name: Generate JSON Schema
        run: make json_schema

      - name: Schema Consistency Check
        run: |
          if [[ $(git diff) ]]
          then
            git diff
            echo 'Failure: JSON schema and generated schema do not match. Run make json_schema and commit the updated schema changes before merge.'
            exit 1
          else
            echo 'Success: JSON schema and generated schema match.'
          fi
