name: Yank PyPI Release

on:

  pull_request:
    types: [opened, synchronize]

jobs:
  yank-release:
    runs-on: ubuntu-latest
    steps:
      - name: Install twine
        run: pip install twine==3.2.0

      - name: Get package name
        id: package-name
        run: |
          # Extract package name from repository name
          REPO_NAME="${{ github.event.repository.name }}"
          # Convert underscores to hyphens for PyPI package names
          PACKAGE_NAME=$(echo "$REPO_NAME" | sed 's/_/-/g')
          echo "package-name=$PACKAGE_NAME" >> $GITHUB_OUTPUT

      - name: Yank release from PyPI
        run: |          
          twine delete dbt-semantic-interfaces -v 0.8.6

        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
